services:
  backend:
    tty: true

    build:
      context: .
      dockerfile: Dockerfile

    container_name: projectgame-backend

    ports:
      - "8000:8000"

    env_file:
      - .env

    environment:
      AWS_SHARED_CREDENTIALS_FILE: /run/aws/credentials
      AWS_CONFIG_FILE: /run/aws/config

    command: >
      uv run uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload

    depends_on:
      - postgres-db

    volumes: 
      - .:/code
      - /code/.venv

      - type: bind
        source: ${USERPROFILE}/.aws/projectgame-credentials
        target: /run/aws/credentials
        read_only: true

      - type: bind
        source: ${USERPROFILE}/.aws/projectgame-config
        target: /run/aws/config
        read_only: true

  postgres-db:
    image: postgres:16

    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: